import type { Metadata } from "next";

import Navbar from "@/components/global/navbar";
import SmoothScrolling from "@/components/providers/smooth-scrolling";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { CursorProvider } from "@/components/test/claude-cursor";
import { geistMono, geistSans, gridular, inter, irishGrover, italiana, jacquard24, kings, kolkerBrush, playfair, poppins, rmMono, rmNeue } from "./fonts/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} ${playfair.variable} ${irishGrover.variable} ${italiana.variable} ${jacquard24.variable} ${kolkerBrush.variable} ${kings.variable} 
         ${gridular.variable} ${rmMono.variable} ${rmNeue.variable}
         antialiased`}
         suppressHydrationWarning
      >
        <SmoothScrolling>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <CursorProvider>
              <Navbar />
              {children}
            </CursorProvider>
          </ThemeProvider>
        </SmoothScrolling>
      </body>
    </html>
  );
}
